channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==2.19.0
  - numpy==2.3.5
  - pandas==2.3.3
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.16.3
  - xgboost==3.1.2
name: mlflow-env
